name: Django application

on: [push]

jobs: 
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_HOST: db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - name: psycopg2-binary prerequisites
      run: sudo apt install libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Lint with flake8
      run: |
        pipenv install --dev
        pipenv run flake8
    - name: Run tests
      run: |
        pipenv run python manage.py test